In [10]:
paragrap = """Arguably one of the best all-rounders this game has ever seen, Shakib Al Hasan is an extraordinary talent and a player for all formats. He has been bossing the ICC Rankings for all-rounders for many years without much competition and has put his name among many greats of the game.


The Magura-born Shakib made his ODI debut in 2006 primarily as a bowler, but over time started concentrating on his batting. However, his bowling talents were re-discovered in the 2008 home Test series against New Zealand where in an exceptional first game, he ran through the Kiwi line-up with figures of 7-37 in the first innings and a fluent 71 in the second innings also reiterated his batting skills. Gradually, he became the undisputed all-rounder in the side. His growth as a player saw him being elevated to vice-captaincy in 2009 and Shakib showed he was up for captaincy when as a stand-in captain for the second Test against West Indies in 2009, he led Bangladesh to their first ever victory on foreign soil.


Mashrafe Mortaza's injury saw Shakib getting a prolonged shot at captaincy and though his stints as the captain had its highs and lows, he continued to come through leaps and bounds as a player. But in mid-2010, he decided to give up captaincy. However, fate had other plans as Mortaza once again fell prey to injury and Shakib was asked to lead the side in the home ODI series against New Zealand in which Bangladesh thrashed the Kiwis by a whopping 4-0 margin. The following year, Bangladesh toured Zimbabwe to play a one-off Test and five ODIs. Under skipper Shakib, the team put up a disastrous performance as Zimbabwe beat them by 136 runs in their only Test and also clinched the ODI series 3-2. Immediate repercussions of the defeat saw Shakib being axed by the Bangladesh Cricket Board.


The all-rounder was signed by the Kolkata franchise in the Indian T20 League for the 2011 season and was retained the following year and did well enough to be bought back in 2014 for the 7th season. After a disastrous World Twenty20 2014 at home, which saw Bangladesh even slump to lowly-ranked Hong Kong in the qualifiers, Shakib suggested that his side should not play home games for two years to help reduce expectations from cricket fans in the country and also expressed his worry for the lack of talent and cricket infrastructure in the country."""

In [11]:
paragrap

"Arguably one of the best all-rounders this game has ever seen, Shakib Al Hasan is an extraordinary talent and a player for all formats. He has been bossing the ICC Rankings for all-rounders for many years without much competition and has put his name among many greats of the game.\n\n\nThe Magura-born Shakib made his ODI debut in 2006 primarily as a bowler, but over time started concentrating on his batting. However, his bowling talents were re-discovered in the 2008 home Test series against New Zealand where in an exceptional first game, he ran through the Kiwi line-up with figures of 7-37 in the first innings and a fluent 71 in the second innings also reiterated his batting skills. Gradually, he became the undisputed all-rounder in the side. His growth as a player saw him being elevated to vice-captaincy in 2009 and Shakib showed he was up for captaincy when as a stand-in captain for the second Test against West Indies in 2009, he led Bangladesh to their first ever victory on foreig

In [12]:
import nltk 
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords

## tokenization paragraph-->sentences--words

In [13]:
nltk.download('punkt')

sentence=nltk.sent_tokenize(paragrap)

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\mahed\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [14]:
print(sentence)

['Arguably one of the best all-rounders this game has ever seen, Shakib Al Hasan is an extraordinary talent and a player for all formats.', 'He has been bossing the ICC Rankings for all-rounders for many years without much competition and has put his name among many greats of the game.', 'The Magura-born Shakib made his ODI debut in 2006 primarily as a bowler, but over time started concentrating on his batting.', 'However, his bowling talents were re-discovered in the 2008 home Test series against New Zealand where in an exceptional first game, he ran through the Kiwi line-up with figures of 7-37 in the first innings and a fluent 71 in the second innings also reiterated his batting skills.', 'Gradually, he became the undisputed all-rounder in the side.', 'His growth as a player saw him being elevated to vice-captaincy in 2009 and Shakib showed he was up for captaincy when as a stand-in captain for the second Test against West Indies in 2009, he led Bangladesh to their first ever victor

In [15]:
type(sentence)

list

In [16]:
stemmer = PorterStemmer()

In [17]:
stemmer.stem()

TypeError: stem() missing 1 required positional argument: 'word'

## now we can also use lemetization

In [18]:
from nltk.stem import WordNetLemmatizer

In [19]:
lemetizer = WordNetLemmatizer()

In [20]:
len(sentence)

14

## cleaning the datas

In [21]:
import re

In [22]:
corpus = []
for i in range(len(sentence)):
    text=re.sub('[^a-zA-Z]', ' ', sentence[i])
    text= text.lower()
    corpus.append(text)
    


In [23]:
type(corpus)

list

In [24]:
corpus

['arguably one of the best all rounders this game has ever seen  shakib al hasan is an extraordinary talent and a player for all formats ',
 'he has been bossing the icc rankings for all rounders for many years without much competition and has put his name among many greats of the game ',
 'the magura born shakib made his odi debut in      primarily as a bowler  but over time started concentrating on his batting ',
 'however  his bowling talents were re discovered in the      home test series against new zealand where in an exceptional first game  he ran through the kiwi line up with figures of      in the first innings and a fluent    in the second innings also reiterated his batting skills ',
 'gradually  he became the undisputed all rounder in the side ',
 'his growth as a player saw him being elevated to vice captaincy in      and shakib showed he was up for captaincy when as a stand in captain for the second test against west indies in       he led bangladesh to their first ever v

In [25]:
import nltk
nltk.download('all')

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to
[nltk_data]    |     C:\Users\mahed\AppData\Roaming\nltk_data...
[nltk_data]    |   Package abc is already up-to-date!
[nltk_data]    | Downloading package alpino to
[nltk_data]    |     C:\Users\mahed\AppData\Roaming\nltk_data...
[nltk_data]    |   Package alpino is already up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     C:\Users\mahed\AppData\Roaming\nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     C:\Users\mahed\AppData\Roaming\nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_ru is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package basque_grammars to
[nltk_data]    |     C:\Users\mahed\AppData\Roaming\nltk_data...
[nltk_data]    | 

[nltk_data]    |   Package movie_reviews is already up-to-date!
[nltk_data]    | Downloading package mte_teip5 to
[nltk_data]    |     C:\Users\mahed\AppData\Roaming\nltk_data...
[nltk_data]    |   Package mte_teip5 is already up-to-date!
[nltk_data]    | Downloading package mwa_ppdb to
[nltk_data]    |     C:\Users\mahed\AppData\Roaming\nltk_data...
[nltk_data]    |   Package mwa_ppdb is already up-to-date!
[nltk_data]    | Downloading package names to
[nltk_data]    |     C:\Users\mahed\AppData\Roaming\nltk_data...
[nltk_data]    |   Package names is already up-to-date!
[nltk_data]    | Downloading package nombank.1.0 to
[nltk_data]    |     C:\Users\mahed\AppData\Roaming\nltk_data...
[nltk_data]    |   Package nombank.1.0 is already up-to-date!
[nltk_data]    | Downloading package nonbreaking_prefixes to
[nltk_data]    |     C:\Users\mahed\AppData\Roaming\nltk_data...
[nltk_data]    |   Package nonbreaking_prefixes is already up-to-date!
[nltk_data]    | Downloading package nps_chat

[nltk_data]    |   Package twitter_samples is already up-to-date!
[nltk_data]    | Downloading package udhr to
[nltk_data]    |     C:\Users\mahed\AppData\Roaming\nltk_data...
[nltk_data]    |   Package udhr is already up-to-date!
[nltk_data]    | Downloading package udhr2 to
[nltk_data]    |     C:\Users\mahed\AppData\Roaming\nltk_data...
[nltk_data]    |   Package udhr2 is already up-to-date!
[nltk_data]    | Downloading package unicode_samples to
[nltk_data]    |     C:\Users\mahed\AppData\Roaming\nltk_data...
[nltk_data]    |   Package unicode_samples is already up-to-date!
[nltk_data]    | Downloading package universal_tagset to
[nltk_data]    |     C:\Users\mahed\AppData\Roaming\nltk_data...
[nltk_data]    |   Package universal_tagset is already up-to-date!
[nltk_data]    | Downloading package universal_treebanks_v20 to
[nltk_data]    |     C:\Users\mahed\AppData\Roaming\nltk_data...
[nltk_data]    |   Package universal_treebanks_v20 is already up-to-
[nltk_data]    |       date!

True

## applying stemming 

In [26]:
for i in corpus:
    words= nltk.word_tokenize(i)
    for word in words:
        if word not in set(stopwords.words('english')):
            print(stemmer.stem(word))

arguabl
one
best
rounder
game
ever
seen
shakib
al
hasan
extraordinari
talent
player
format
boss
icc
rank
rounder
mani
year
without
much
competit
put
name
among
mani
great
game
magura
born
shakib
made
odi
debut
primarili
bowler
time
start
concentr
bat
howev
bowl
talent
discov
home
test
seri
new
zealand
except
first
game
ran
kiwi
line
figur
first
inning
fluent
second
inning
also
reiter
bat
skill
gradual
becam
undisput
rounder
side
growth
player
saw
elev
vice
captainci
shakib
show
captainci
stand
captain
second
test
west
indi
led
bangladesh
first
ever
victori
foreign
soil
mashraf
mortaza
injuri
saw
shakib
get
prolong
shot
captainci
though
stint
captain
high
low
continu
come
leap
bound
player
mid
decid
give
captainci
howev
fate
plan
mortaza
fell
prey
injuri
shakib
ask
lead
side
home
odi
seri
new
zealand
bangladesh
thrash
kiwi
whop
margin
follow
year
bangladesh
tour
zimbabw
play
one
test
five
odi
skipper
shakib
team
put
disastr
perform
zimbabw
beat
run
test
also
clinch
odi
seri
immedi
reper

## lemetization

In [38]:
for i in corpus:
    words= nltk.word_tokenize(i)
    for word in words:
        if word not in set(stopwords.words('english')):
            print(lemetizer.lemmatize(word))

arguably
one
best
rounder
game
ever
seen
shakib
al
hasan
extraordinary
talent
player
format
bossing
icc
ranking
rounder
many
year
without
much
competition
put
name
among
many
great
game
magura
born
shakib
made
odi
debut
primarily
bowler
time
started
concentrating
batting
however
bowling
talent
discovered
home
test
series
new
zealand
exceptional
first
game
ran
kiwi
line
figure
first
inning
fluent
second
inning
also
reiterated
batting
skill
gradually
became
undisputed
rounder
side
growth
player
saw
elevated
vice
captaincy
shakib
showed
captaincy
stand
captain
second
test
west
indie
led
bangladesh
first
ever
victory
foreign
soil
mashrafe
mortaza
injury
saw
shakib
getting
prolonged
shot
captaincy
though
stint
captain
high
low
continued
come
leap
bound
player
mid
decided
give
captaincy
however
fate
plan
mortaza
fell
prey
injury
shakib
asked
lead
side
home
odi
series
new
zealand
bangladesh
thrashed
kiwi
whopping
margin
following
year
bangladesh
toured
zimbabwe
play
one
test
five
odis
skipper

## bag of words 

In [28]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(binary=True)

In [29]:
x = cv.fit_transform(corpus)

In [30]:
cv.vocabulary_

{'arguably': 9,
 'one': 125,
 'of': 121,
 'the': 174,
 'best': 22,
 'all': 4,
 'rounders': 147,
 'this': 177,
 'game': 68,
 'has': 76,
 'ever': 50,
 'seen': 152,
 'shakib': 154,
 'al': 3,
 'hasan': 77,
 'is': 94,
 'an': 7,
 'extraordinary': 54,
 'talent': 168,
 'and': 8,
 'player': 132,
 'for': 63,
 'formats': 65,
 'he': 78,
 'been': 20,
 'bossing': 25,
 'icc': 86,
 'rankings': 140,
 'many': 110,
 'years': 204,
 'without': 200,
 'much': 115,
 'competition': 36,
 'put': 136,
 'his': 82,
 'name': 116,
 'among': 6,
 'greats': 73,
 'magura': 109,
 'born': 24,
 'made': 108,
 'odi': 119,
 'debut': 41,
 'in': 88,
 'primarily': 134,
 'as': 10,
 'bowler': 28,
 'but': 30,
 'over': 128,
 'time': 181,
 'started': 165,
 'concentrating': 37,
 'on': 123,
 'batting': 16,
 'however': 85,
 'bowling': 29,
 'talents': 169,
 'were': 193,
 're': 141,
 'discovered': 46,
 'home': 83,
 'test': 171,
 'series': 153,
 'against': 2,
 'new': 117,
 'zealand': 205,
 'where': 196,
 'exceptional': 51,
 'first': 59,
 'r

In [31]:
corpus[0]

'arguably one of the best all rounders this game has ever seen  shakib al hasan is an extraordinary talent and a player for all formats '

In [32]:
x[0].toarray()

array([[0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

In [33]:
corpus=[]
for i in range(len(sentence)):
    r = re.sub('[^a-zA-Z]', ' ', sentence[i])
    r = r.lower()
    r = r.split()
    r = [lemetizer.lemmatize(word) for word in r if not word in set(stopwords.words('english'))]
    r = ' '.join(r)
    corpus.append(r)

In [34]:
y = cv.fit_transform(corpus)

In [35]:
cv.vocabulary_

{'arguably': 3,
 'one': 94,
 'best': 11,
 'rounder': 111,
 'game': 52,
 'ever': 36,
 'seen': 116,
 'shakib': 118,
 'al': 0,
 'hasan': 58,
 'extraordinary': 40,
 'talent': 131,
 'player': 98,
 'format': 50,
 'bossing': 14,
 'icc': 64,
 'ranking': 106,
 'many': 84,
 'year': 150,
 'without': 147,
 'much': 89,
 'competition': 23,
 'put': 102,
 'name': 90,
 'among': 2,
 'great': 56,
 'magura': 83,
 'born': 13,
 'made': 82,
 'odi': 92,
 'debut': 28,
 'primarily': 100,
 'bowler': 17,
 'time': 137,
 'started': 128,
 'concentrating': 24,
 'batting': 8,
 'however': 63,
 'bowling': 18,
 'discovered': 32,
 'home': 61,
 'test': 133,
 'series': 117,
 'new': 91,
 'zealand': 151,
 'exceptional': 37,
 'first': 45,
 'ran': 104,
 'kiwi': 71,
 'line': 79,
 'figure': 44,
 'inning': 70,
 'fluent': 47,
 'second': 115,
 'also': 1,
 'reiterated': 108,
 'skill': 123,
 'gradually': 55,
 'became': 10,
 'undisputed': 141,
 'side': 121,
 'growth': 57,
 'saw': 113,
 'elevated': 33,
 'vice': 142,
 'captaincy': 20,
 '

In [36]:
corpus[0]

'arguably one best rounder game ever seen shakib al hasan extraordinary talent player format'

In [37]:
y[0].toarray()

array([[1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int64)

In [39]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(binary=True, ngram_range=(3,3))

In [40]:
N_gram = cv.fit_transform(corpus)

In [42]:
cv.vocabulary_

{'arguably one best': 5,
 'one best rounder': 110,
 'best rounder game': 16,
 'rounder game ever': 130,
 'game ever seen': 60,
 'ever seen shakib': 43,
 'seen shakib al': 141,
 'shakib al hasan': 143,
 'al hasan extraordinary': 0,
 'hasan extraordinary talent': 66,
 'extraordinary talent player': 48,
 'talent player format': 164,
 'bossing icc ranking': 18,
 'icc ranking rounder': 76,
 'ranking rounder many': 125,
 'rounder many year': 131,
 'many year without': 99,
 'year without much': 187,
 'without much competition': 181,
 'much competition put': 104,
 'competition put name': 29,
 'put name among': 121,
 'name among many': 105,
 'among many great': 4,
 'many great game': 98,
 'magura born shakib': 97,
 'born shakib made': 17,
 'shakib made odi': 147,
 'made odi debut': 96,
 'odi debut primarily': 108,
 'debut primarily bowler': 34,
 'primarily bowler time': 118,
 'bowler time started': 20,
 'time started concentrating': 172,
 'started concentrating batting': 159,
 'however bowling 

In [41]:
N_gram[0].toarray()

array([[1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

## TF-IDF

In [43]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf= TfidfVectorizer()

In [44]:
hhh= tf.fit_transform(corpus)

In [45]:
corpus[0]

'arguably one best rounder game ever seen shakib al hasan extraordinary talent player format'

In [46]:
hhh[0].toarray()

array([[0.30282896, 0.        , 0.        , 0.30282896, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.30282896, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.26210241, 0.        , 0.        , 0.        ,
        0.30282896, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.30282896, 0.        , 0.21079304, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.30282896, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.  