<a href="https://colab.research.google.com/github/mahedishato/Natural_language_processing/blob/main/NLP_practice_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [43]:
!pip install tensorflow-gpu

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [44]:
import tensorflow as tf
print(tf.__version__)

2.11.0


In [45]:
from tensorflow.keras.preprocessing.text import one_hot

In [46]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [47]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [48]:
voc_size = 22

In [49]:
 one_hot= [one_hot(words,voc_size)for words in sent]

In [50]:
one_hot

[[14, 9, 6, 14],
 [14, 9, 6, 3],
 [14, 3, 6, 6],
 [15, 13, 12, 9, 5],
 [15, 13, 12, 9, 1],
 [14, 14, 7, 6, 12],
 [11, 21, 12, 9]]

In [51]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [52]:
sent_len = 10
embedded_docs = pad_sequences(one_hot,maxlen=sent_len,padding='pre')

In [53]:
embedded_docs

array([[ 0,  0,  0,  0,  0,  0, 14,  9,  6, 14],
       [ 0,  0,  0,  0,  0,  0, 14,  9,  6,  3],
       [ 0,  0,  0,  0,  0,  0, 14,  3,  6,  6],
       [ 0,  0,  0,  0,  0, 15, 13, 12,  9,  5],
       [ 0,  0,  0,  0,  0, 15, 13, 12,  9,  1],
       [ 0,  0,  0,  0,  0, 14, 14,  7,  6, 12],
       [ 0,  0,  0,  0,  0,  0, 11, 21, 12,  9]], dtype=int32)

In [54]:
model= Sequential()

In [55]:
model.add(Embedding(22,10,input_length=sent_len))
model.compile('adam', 'mse')

In [56]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_3 (Embedding)     (None, 10, 10)            220       
                                                                 
Total params: 220
Trainable params: 220
Non-trainable params: 0
_________________________________________________________________


In [57]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 70ms/step


array([[[ 0.01865378, -0.01250862, -0.04433106, -0.03098797,
         -0.02499311, -0.0359871 ,  0.01182093,  0.02826465,
          0.00845452,  0.00490402],
        [ 0.01865378, -0.01250862, -0.04433106, -0.03098797,
         -0.02499311, -0.0359871 ,  0.01182093,  0.02826465,
          0.00845452,  0.00490402],
        [ 0.01865378, -0.01250862, -0.04433106, -0.03098797,
         -0.02499311, -0.0359871 ,  0.01182093,  0.02826465,
          0.00845452,  0.00490402],
        [ 0.01865378, -0.01250862, -0.04433106, -0.03098797,
         -0.02499311, -0.0359871 ,  0.01182093,  0.02826465,
          0.00845452,  0.00490402],
        [ 0.01865378, -0.01250862, -0.04433106, -0.03098797,
         -0.02499311, -0.0359871 ,  0.01182093,  0.02826465,
          0.00845452,  0.00490402],
        [ 0.01865378, -0.01250862, -0.04433106, -0.03098797,
         -0.02499311, -0.0359871 ,  0.01182093,  0.02826465,
          0.00845452,  0.00490402],
        [-0.02507961,  0.00224849, -0.02595519,  0.0

In [59]:
embedded_docs[0]

array([ 0,  0,  0,  0,  0,  0, 14,  9,  6, 14], dtype=int32)

In [58]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 36ms/step


array([[ 0.01865378, -0.01250862, -0.04433106, -0.03098797, -0.02499311,
        -0.0359871 ,  0.01182093,  0.02826465,  0.00845452,  0.00490402],
       [ 0.01865378, -0.01250862, -0.04433106, -0.03098797, -0.02499311,
        -0.0359871 ,  0.01182093,  0.02826465,  0.00845452,  0.00490402],
       [ 0.01865378, -0.01250862, -0.04433106, -0.03098797, -0.02499311,
        -0.0359871 ,  0.01182093,  0.02826465,  0.00845452,  0.00490402],
       [ 0.01865378, -0.01250862, -0.04433106, -0.03098797, -0.02499311,
        -0.0359871 ,  0.01182093,  0.02826465,  0.00845452,  0.00490402],
       [ 0.01865378, -0.01250862, -0.04433106, -0.03098797, -0.02499311,
        -0.0359871 ,  0.01182093,  0.02826465,  0.00845452,  0.00490402],
       [ 0.01865378, -0.01250862, -0.04433106, -0.03098797, -0.02499311,
        -0.0359871 ,  0.01182093,  0.02826465,  0.00845452,  0.00490402],
       [-0.02507961,  0.00224849, -0.02595519,  0.0127015 ,  0.0029764 ,
         0.00337465, -0.01710813,  0.04771943