In [1]:
from keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(oov_token='<nothing>')

In [2]:
import numpy as np
from keras.datasets import imdb
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [3]:
(X_train,y_train),(X_test,y_test) = imdb.load_data()

In [ ]:
X_train[0]

In [5]:
len(X_train[2])

141

In [6]:
from keras.utils import pad_sequences
X_train = pad_sequences(X_train,padding='post',maxlen=50)
X_test = pad_sequences(X_test,padding='post',maxlen=50)

In [7]:
len(X_train[2])

50

In [8]:
len(X_train[7])

50

In [9]:
X_train[0]

array([2071,   56,   26,  141,    6,  194, 7486,   18,    4,  226,   22,
         21,  134,  476,   26,  480,    5,  144,   30, 5535,   18,   51,
         36,   28,  224,   92,   25,  104,    4,  226,   65,   16,   38,
       1334,   88,   12,   16,  283,    5,   16, 4472,  113,  103,   32,
         15,   16, 5345,   19,  178,   32], dtype=int32)

In [10]:
X_test.shape

(25000, 50)

In [11]:
X_train.shape

(25000, 50)

In [12]:
y_train.shape

(25000,)

In [13]:
y_test.shape

(25000,)

In [14]:
model = Sequential()
model.add(Embedding(10000,output_dim=2,input_length=50))
model.add(SimpleRNN(32,input_shape=(50,1),return_sequences=False))
model.add(Dense(1,activation='sigmoid'))

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 50, 2)             20000     
                                                                 
 simple_rnn (SimpleRNN)      (None, 32)                1120      
                                                                 
 dense (Dense)               (None, 1)                 33        
                                                                 
Total params: 21,153
Trainable params: 21,153
Non-trainable params: 0
_________________________________________________________________


In [ ]:
!pip install tensorflow==2.9.1

In [ ]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
model.fit(X_train,y_train,epochs=5,steps_per_epoch=len(X_train),validation_data=(X_test,y_test))

In [48]:
import numpy as np

docs = ['go bangladesh',
		'bangladesh bangladesh',
		'hip hip hurray',
		'jitbe bhai jitbe bangladesh jitbe',
		'bangladesher joy hobe',
		'sakib sakib',
		'miraz miraz',
		'liton liton',
		'pm khela dekhtese',
		'bangladesh zindabad']

In [49]:
tokenizer.fit_on_texts(docs)

In [58]:
from tensorflow.keras.preprocessing.text import one_hot

In [61]:
one_hot= [one_hot(words,20)for words in docs]

In [62]:
one_hot

[[9, 4],
 [4, 4],
 [14, 14, 15],
 [17, 13, 17, 4, 17],
 [14, 12, 17],
 [18, 18],
 [15, 15],
 [2, 2],
 [19, 7, 17],
 [4, 16]]

In [63]:
sent_len = 10
embedded_docs = pad_sequences(one_hot,maxlen=sent_len,padding='pre')


In [64]:
embedded_docs

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  9,  4],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  4,  4],
       [ 0,  0,  0,  0,  0,  0,  0, 14, 14, 15],
       [ 0,  0,  0,  0,  0, 17, 13, 17,  4, 17],
       [ 0,  0,  0,  0,  0,  0,  0, 14, 12, 17],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 18, 18],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 15, 15],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  2,  2],
       [ 0,  0,  0,  0,  0,  0,  0, 19,  7, 17],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  4, 16]], dtype=int32)

In [69]:
model= Sequential()
model.add(Embedding(20,5,input_length=sent_len))
model.compile('adam', 'mse')

In [ ]:
model.predict(embedded_docs)

In [71]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 37ms/step


array([[ 0.00858504,  0.04196269,  0.04282169, -0.00631012, -0.02910385],
       [ 0.00858504,  0.04196269,  0.04282169, -0.00631012, -0.02910385],
       [ 0.00858504,  0.04196269,  0.04282169, -0.00631012, -0.02910385],
       [ 0.00858504,  0.04196269,  0.04282169, -0.00631012, -0.02910385],
       [ 0.00858504,  0.04196269,  0.04282169, -0.00631012, -0.02910385],
       [ 0.00858504,  0.04196269,  0.04282169, -0.00631012, -0.02910385],
       [ 0.00858504,  0.04196269,  0.04282169, -0.00631012, -0.02910385],
       [ 0.00858504,  0.04196269,  0.04282169, -0.00631012, -0.02910385],
       [ 0.03553635, -0.04449042, -0.00266588,  0.01417453,  0.04095856],
       [-0.00664252,  0.00067898, -0.02074164, -0.04695065,  0.02197165]],
      dtype=float32)

In [72]:
import numpy as np

data = ['go bangladesh',
		'bangladesh bangladesh',
		'hip hip hurray',
		'jitbe bhai jitbe bangladesh jitbe',
		'bangladesher joy hobe',
		'sakib sakib',
		'miraz miraz',
		'liton liton',
		'pm khela dekhtese',
		'bangladesh zindabad']

In [73]:
tokenizer.fit_on_texts(data)

In [74]:
sequences = tokenizer.texts_to_sequences(data)
sequences

[[8, 2],
 [2, 2],
 [4, 4, 9],
 [3, 10, 3, 2, 3],
 [11, 12, 13],
 [5, 5],
 [6, 6],
 [7, 7],
 [14, 15, 16],
 [2, 17]]

In [75]:
maximumlenth_of_document= 5
sequences = pad_sequences(sequences,padding='pre', maxlen=maximumlenth_of_document)

In [76]:
sequences

array([[ 0,  0,  0,  8,  2],
       [ 0,  0,  0,  2,  2],
       [ 0,  0,  4,  4,  9],
       [ 3, 10,  3,  2,  3],
       [ 0,  0, 11, 12, 13],
       [ 0,  0,  0,  5,  5],
       [ 0,  0,  0,  6,  6],
       [ 0,  0,  0,  7,  7],
       [ 0,  0, 14, 15, 16],
       [ 0,  0,  0,  2, 17]], dtype=int32)

In [77]:
models= Sequential()
models.add(Embedding(10000,10,input_length=maximumlenth_of_document))
models.compile('adam', 'mse')

In [ ]:
models.predict(sequences)

In [79]:
models.predict(sequences[0])

1/1 [==============================] - 0s 70ms/step


array([[-0.00434513,  0.04946568,  0.02676019, -0.0273748 , -0.03880227,
        -0.00649433,  0.03395304,  0.02671862, -0.04983112,  0.00773877],
       [-0.00434513,  0.04946568,  0.02676019, -0.0273748 , -0.03880227,
        -0.00649433,  0.03395304,  0.02671862, -0.04983112,  0.00773877],
       [-0.00434513,  0.04946568,  0.02676019, -0.0273748 , -0.03880227,
        -0.00649433,  0.03395304,  0.02671862, -0.04983112,  0.00773877],
       [ 0.03741587,  0.03745378, -0.02737266,  0.02064489, -0.01188482,
        -0.04176688, -0.02558756, -0.00105613,  0.04623229, -0.03512601],
       [-0.03020774,  0.01363934, -0.0312997 ,  0.02954752, -0.015693  ,
         0.04496196,  0.03770126,  0.04069031,  0.02541341,  0.0465968 ]],
      dtype=float32)